### ISSUE TITLE
File format PES files

### ISSUE THREAD

**Issue by roelderickx** [roelderickx/retro-testdrive#1]
The 16-color PES files have a different file format compared to the 4-color CMP files.

First of all there is a 16 byte header:
```
struct Header {
    char   magic[4] // "Pckd"
    uint32 compressed_size
    uint32 uncompressed_size
    uint8 unknown1 // 0x08
    uint8 unknown2 // 0x00
    uint8 unknown3
    uint8 unknown4

    uint8  data[...]
}
```
The reason we know the header contains 16 bytes is the fact that compressed_size contains the filesize - 16.

The data always starts with 0x0c. Maybe unrelated, but [the stunts wiki](https://wiki.stunts.hu/wiki/Compression#0xC_Obfuscation) links this code to some kind of obfuscation. And that's what it seems to be if we look at the first bytes of the obfuscated data compared to the first bytes of the 4-color CMP file, since they contain the same sprites the index should be the same as well. A CMP-file starts with the uncompressed file size, in the example below it is modified to reflect the uncompressed_size from the header.

Original:
```
00000000  8b cc 00 00 1c 00 62 6c  6e 6b 63 61 72 00 66 72  |......blnkcar.fr|
00000010  6d 41 66 72 6d 42 66 72  6d 43 66 72 6d 6d 67 63  |mAfrmBfrmCfrmmgc|
00000020  61 72 6e 61 6d 65 72 72  6d 41 72 72 6d 42 72 72  |arnamerrmArrmBrr|
00000030  6d 43 72 72 6d 6d 73 74  61 74 77 6e 64 41 77 6e  |mCrrmmstatwndAwn|
00000040  64 42 77 6e 64 43 77 6e  64 44 77 6e 64 45 77 6e  |dBwndCwndDwndEwn|
00000050  64 46 77 6e 64 47 77 6e  64 48 77 6e 64 49 77 6e  |dFwndGwndHwndIwn|
00000060  64 4a 77 6e 64 4b 77 6e  64 4c 77 6e 64 4d 77 6e  |dJwndKwndLwndMwn|
00000070  64 4e 77 6e 64 4f                                 |dNwndO          |
```

Obfuscated:
```
00000000  8b 98 01 00 30 01 80 18  36 6e d6 8c 09 23 07 80  |....0...6n...#..|
00000020  19 39 6d 82 3c 6c 23 64  e2 90 33 0b e5 b8 09 d3  |.9m.<l#d..3.....|
00000030  a6 8c 1c 88 41 3e 52 14  39 64 0e 9d 30 74 ee b8  |....A>R.9d..0t..|
00000040  21 13 44 25 19 21 2e 87  b8 24 e2 b2 88 4b 23 2e  |!.D%.!...$...K#.|
00000050  8f b8 44 02 00 12 01 08  3d 07 94 c8 30 90 95 86  |..D.....=...0...|
00000060  81 33 38 0c d4 d5 61 a0  06 20 03 f7 41 05 20 48  |.38...a.. ..A. H|
00000070  c8 c0 04 44 06 42 02 50  64 20 08 3d 03 bf 09 1a  |...D.B.Pd .=....|
00000080  08 65 d1 c0 60 93                                 |.e..`.          |
```

The first byte is copied over, which suggests the obfuscation of each following byte is related to its predecessor(s). There is probably also a relation with unknown3 and unknown4 found in the header (respectively 0x3a and 0x22).
We can also see that the second byte 0xcc multiplied by 2 equals 0x0198, to be found in the obfuscated version. It may be coincidence but it is the case for all PES files. Beyond the second byte the obfuscation algorithm is unclear.

**Comment by roelderickx** [comment]
The data does not always start with 0x0c, but let's not focus on the single file where the data starts with 0x0f for now.
If the data starts with 0x0c, every 9 bytes contain 8 output bytes each separated by a single bit, resulting in:
```
00000000  8b cc 00 00 13 00 62 6c  6e 6b 63 61 72 00 66 72  |......blnkcar.fr|
00000010  6d 41 0f 6d 42 13 43 67  0b 72 6e 61 6d 65 72 10  |mA.mB.Cg.rnamer.|
00000020  41 1f 14 22 43 73 74 61  74 77 6e 64 41 2a 64 42  |A.."CstatwndA*dB|
00000030  2e 43 2e 44 2e 45 2e 46  2e 47 2e 48 00 90 04 10  |.C.D.E.F.G.H....|
00000040  3d 03 25 19 03 ac 1a 03  33 1c 03 ba 1d 03 1a 40  |=.%.....3......@|
00000050  03 fb 50 00 82 42 03 09  44 03 90 00 45 03 20 7a  |..P..B..D...E. z|
00000060  03 df 82 03 50 8b 03 c1  93 03 fd 9e 03 39 aa 03  |....P........9..|
00000070  75 b5 03 b1 c0 03 0b 04  3d 09 f0 41 23 00 3d 41  |u.......=..A#.=A|
00000080  17 00 40 0e 00 09 02 04  3d 18 0a 80 3d 05 01 ff  |..@.....=...=...|
00000090  df e0 3d 10 03 ff 3e df  ff 55 4f d4 3d 04 2b fe  |..=...>..UO.=.+.|
```
There is some basic compression, the byte at pos 0x12 is clearly the offset where the bytes to be filled in can be found: positions 0x0e and 0x0f contain `fr`. It is not clear how many characters must be filled in and what the offset exactly means. Can it be a relative position? Can it be 2 positions long? Is it counted on compressed or uncompressed data?

**Comment by dstien** [comment]
Hi @roelderickx,
The detailed error handling and messages for the decompression code in TDEGA.EXE looks very out of character for DSI. It appears to come from [ARC](https://en.wikipedia.org/wiki/ARC_(file_format)), with this modified header:

```
struct Header {
    char   magic[4] // "Pckd"
    uint32 compressed_size
    uint32 uncompressed_size
    uint16 method
    uint16 unknown
}
```

The unknown field appears to be ignored. Maybe it's the 16-bit CRC used by ARC?

The compression methods supported by TD1 are:
* 2: "Standard packing"
* 3: "Non-repeat packing"
* 4: "Huffman squeezing"
* 8: "Dynamic Lempel-Ziv"

In TD1 every packed EGA shape file uses method 8 (LZ), except TESTDRV.PES which uses 4 (Huffman). I haven't tested it myself yet, but it [looks](https://github.com/hyc/arc/blob/325047b2dc60fad5f6c8238d8cb5294b9a5ada38/arcunp.c#L68) compelling. This is very interesting and may put the origin of the other compression methods used by DSI/EAC in new light!

**Comment by roelderickx** [comment]
Hi @dstien, thanks for the information.

Meanwhile I figured the extra bit between the bytes indicates either copy the preceding byte (in case of 0) or replace by a sequence found somewhere else (in case of 1). I am not an expert in compression -- I only have a basic understanding of huffman trees -- but what I found looks indeed as Lempel-Ziv compression. More specific [LZSS](https://en.wikipedia.org/wiki/Lempel%E2%80%93Ziv%E2%80%93Storer%E2%80%93Szymanski).

I'll try the code you linked before writing a complete implementation in Python, which may not be the best language for this purpose anyway. That being said, I just want to understand the file format in stead of having a useful implementation.

**Comment by roelderickx** [comment]
@dstien As expected, you were totally right about the compression.

I had to convert to PES files to ARC files first, I wrote a quick and dirty converter to convert the header (see pes2arc.py). The resulting files all unpack nicely with [arc](https://github.com/hyc/arc) and the uncompressed contents seem to make sense. The unknown uint16 turned out to be the CRC checksum as you assumed already.

I'll have a look to extract the sprites during the weekend, but I don't expect it to be difficult anymore.

**Comment by roelderickx** [comment]
The code to extract the sprites from Grand Prix / Cycles can be used for Test Drive as well, but not all features are used. There are no vertically stored layers and no colors to be suppressed from the background color.
However, the palette seems to be different. The entire game does not contain a single bright magenta pixel, which frees up a color to be used as mask. I had to play around a bit to reorder the colors, it is more or less correct now. Some details in XROADC are brown which should be bright red, it's especially notable for the rear lights of the vehicles.

Documentation to be written out, but that's for another time :-)
